### ISSUE TITLE
use the wiki and issues tracker

### ISSUE THREAD

**Issue by jpuck** [MakingTrevenue/uark-mis#2]
Instead of coding your todo list and other notes on the home page, you should take advantage of the repository's built-in wiki on Github and add your team members as collaborators. Also, take advantage of the issues (like this one) to track project deliverables, bugs, and milestones. It's very useful.

**Comment by MakingTrevenue** [comment]
Moved list to Wiki page and added Eric Newsom as a collaborator. Will utilize issue tracker where possible instead of just our Kanban board.
